apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kraft
  labels:
    strimzi.io/cluster: my-cluster
    app.kubernetes.io/part-of: event-platform
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
