{{- $ns := include "event-platform.namespace" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-gateway-sa
  namespace: {{ $ns }}
  labels:
    {{- include "event-platform.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-worker-sa
  namespace: {{ $ns }}
  labels:
    {{- include "event-platform.labels" . | nindent 4 }}